### ISSUE TITLE
Composing State-Aware Functions (as an Alternative to Objects)

### ISSUE THREAD

**Issue by SchlenkR** [amplifying-fsharp/sessions#10]
Functional programming is known and loved for its simplicity and conciseness. Even if many developers have not yet had contact with pure or "functional-first" languages, their ideas and concepts have long since found their way into mainstream languages and it is hard to imagine devloping without them. Well-known are, for example, LINQ (.Net) or map/filter in JS/TS in the context of lists, through which a calculation is described by assembling individual building blocks (i.e. stateless functions). This principle works well and is very comfortable to use. But let us think of systems such as user interfaces, (recurrent) neural networks, digital signal processing (DSP), simulation of complex systems, game engines or persistable functions, which inherently consist of building blocks that are based on their own (changing) values of past evaluations. Here, known principles of functional programming seem to reach their limits. Recourse to objects - i.e. uniquely addressable, changeable data, revisitable multiple times or by multiple viewers - seems unavoidable here, and even if composability and predictability are also possible with objects if modelled carefully, their use lead to noticeable and unavoidable disadvantages.

The lecture shows an alternative to object-oriented programming with the aim of combining the familiar comfort of functional programming with the fundamental characteristics of stateful systems. It doesn't take much: a little clarification of terms followed by live coding illustrates the incredible versatility of F#, which, according to the speaker, resides in the "sweet spot of practicality".

P.S.: This is the first of two lectures on the basics and practical principles. In the second lecture, a prototype of a React-like UI library based on the ideas from Vide-4-Fable will be developed in live coding.

----

German Version:

Functional programming is known and loved for it's simplicity and conciceness. Auch wenn viele Entwickler noch keine Berührung mit puren oder "funktional-first"-Sprachen gemacht haben, so haben deren Ideen und Konzepte längst Einzug in Mainstream-Sprachen erhalten und sind aus diesen kaum mehr wegzudenken. Bekannt sind z.B. LINQ (.Net) bzw. map/filter (TS/JS) im Kontext von Listen, durch die eine Berechnung durch Zusammensetzen einzelner Bausteine (hier: zustandslose Funktionen) beschrieben wird. Dieses Prinzip funktioniert gut und ist sehr komfortabel in der Handhabung. Doch denken wir an Systeme wie z.B. Benutzeroberflächen, (rekurrente) neuronale Netze, Elemente aus der Signalverarbeitung (DSP), Simulation komplexer Systeme oder persistierbare Funktionen, welche inhärent - also prinzipbedingt - aus Bausteinen bestehen, die auf Eigenwerten vergangener Auswertungen (also lokalem Zustand) basieren. Hier scheinen bekannte Prinzipiel funktionaler Programmierung an ihre Grenzen zu stoßen. Der Rückgriff auf Objekte - also eindeutig adressierbare, änderliche Daten - scheint hier unvermeidbar und auch wenn Composability und Predictability bei vorsichtiger Modellierung auch mit Objekten möglich ist, bringt deren Einsatz prinzipbedingte und spürbare Nachteile mit sich.

Der Vortrag zeigt eine Alternative zu objektorientierter Programmierung mit dem Ziel, den gewohnten Kompfort funktionaler Programmierung mit dem grundlegenden Charakteristika zustandsbehafteter Systeme mit Mehrfachauswertbarkeit zu vereint. Dabei braucht es nicht viel: Ein wenig Begriffsklärung mit anschließendem Live-Coding verdeutlicht die unglaubliche Vielseitigkeit von F#, welche nach Meinung des Vortragenden im "Sweetspot  der Praxisnähe" residiert.

P.S.: Dies ist der 1. Vortrag von zweien zur Vermittlung von Grundlagen und praktischer Prinzipien. Im Zweiten Vortrag wird ein darauf aufbauend im Live-Coding der Prototyp einer React-mäßigen UI-Library entwickelt werden, der sich an den Ideen aus Vide-4-Fable orientiert.

**Comment by dawedawe** [comment]
Hey Ronald,
that's great, thanks a lot. I'll create a draft session page for you to review.

**Comment by SchlenkR** [comment]
Thank you David.
