### ISSUE TITLE
New session about Web, Desktop and Mobile App in F#

### ISSUE THREAD

**Issue by twuttiwat** [amplifying-fsharp/sessions#21]
### Session on Web, Desktop and Mobile App in F#

Teerawat Wuttiwat in GMT+7 would like to tackle:
Develop real world application using F#. It can be either Web, Desktop or Mobile app.

#### Extra

I have worked in C# for almost 20 years. Recently, I have switched to F# and have develop Web application using F# Safe stack. 
I love functional programming in general. I start with Haskell in my university. I also like to try Elm and Phoenix as well.

**Comment by dawedawe** [comment]
Hello @twuttiwat ,
thanks a lot for reaching out to us.

Could you describe a bit more what you have in mind for your session?
For eample, do you want to work on an issue of a library you use or something like that?

**Comment by twuttiwat** [comment]
Hi @dawedawe,

Thanks for replying. I just want to start contribute to F# community in general. But I do not know where to start. Currently, I am interested in following library Fable, Safe-stack, and probably any desktop library (Fabulous or AvaloniaFunc)

Thanks again,
T

**Comment by dawedawe** [comment]
Hey @twuttiwat ,
@edgarfgp would like to do some pair programming with you during your AF session. He has plenty of experience in Fabulous etc. So I'm sure you two will come up with a cool topic for the session.

**Comment by twuttiwat** [comment]
Cool @dawedawe , please let me know anything I need to prepare. I never code in Fabulous or Xamarin before. Only Winform and standard Html stuff. (Html/Js/Css and a bit of React)

**Comment by dawedawe** [comment]
Sure. The next couple of sessions are mostly planned out already, but we'll get in touch with you again soon to talk about details.

**Comment by edgarfgp** [comment]
@twuttiwat . We have scheduled a session https://amplifying-fsharp.github.io/sessions/2023/10/06/. Hope to see you there where we can talk all about F# Desktop + Mobile state of the union.
