### ISSUE TITLE
New session about Solar position calculation 

### ISSUE THREAD

**Issue by houstonhaynes** [amplifying-fsharp/sessions#23]
### Session on Solar position calculation 

Houston Haynes in GMT - 4/5 (US Eastern Time Zone) would like to tackle:
I'm building a solar panel "tracker" that dynamically positions throughout the day in order to maximize the amount of power collected. The (F#) code will run on a WildernessLabs Meadow microcontroller, which is both measuring the position of the panel while controlling its position with a motor control. Since the angles for a given time-of-day change throughout the year, this will end up being a dynamic control that depends on date and location, all of which the microcontroller must collect in order to "do its job" accurately. It's an interesting problem that requires some pretty involved math - so it's a nice combination of "theory" that's grounded in a recognizable real-world scenario.

#### Extra

I'm using the CoordinateSharp library, but there are limits to its function right now. Part of what I'm calculating "manually" in F# will likely be replaced with library functions, built by someone who knows this domain much more than I do. But this "interim" solution that I've built in F# (with help from GitHub Copilot and ChatGPT, I might add) will work for about 90 days or so - dumb luck on my part that I'm starting this at "high summer" in the northern hemisphere. So the F# "hack" I've put together will give me *enough* accuracy in repositioning the panel to give me some "runway" until a more generalized solution is available. That means either CoordinateSharp gets an update, I find another library that can calculate "Obliquity of Ecliptic" and "Equation of Time" functions accurately, or I get enough of the math refreshed in my brain that I build it myself "natively" in F#. :-)

https://github.com/Tronald/CoordinateSharp/issues/222#issuecomment-1642294749

**Comment by dawedawe** [comment]
Hey @houstonhaynes,
thanks a lot for this session proposal. It sounds super interesting to me 👀 

We'll get in touch with you to talk about the details of your session.
But as today will be our last session before we do a summer break, it will most likely be a few weeks...

**Comment by houstonhaynes** [comment]
That's totally cool! It will give me a little bit of Runway to sort a few things out and maybe smooth the rough edges before we go on camera :-)

**Comment by edgarfgp** [comment]
Hi @houstonhaynes, would September 15th work for you? We usually have the session around 3 PM CEST.

**Comment by houstonhaynes** [comment]
> Hi @houstonhaynes, would September 15th work for you? We usually have the session around 3 PM CEST.

That will be great. I have Elmish working in Wilderness Labs Meadow thanks to a big contribution from Jordan Marr (author of Elmish.Avalonia). So it may be worthwhile to include him if he's available at that time. I believe he is in a location close to me (Eastern US time zone).

**Comment by dawedawe** [comment]
Sure. Let's try: Hey @JordanMarr, do you want to join?

**Comment by JordanMarr** [comment]
Hi guys! Thanks, but I think I will observe from the sidelines. Really looking forward to learning more about Houston's project via the interview though! (Because I don't know very much about it. 😅)

**Comment by dawedawe** [comment]
Happened today :)
Thanks again. It was great.

**Comment by houstonhaynes** [comment]
Awesome - thanks! If you can tweak that cover image on YouTube to *not* use a pic of me mid-syllable (looking like I'm half asleep) that would be great! :) Maybe something showing the project board image?

**Comment by dawedawe** [comment]
Youtube has some processing issues right now. But I was able to upload a png for the cover image. If you send me some file I can upload that.
