### ISSUE TITLE
New session about Improve compiler error inside CE for missed match case

### ISSUE THREAD

**Issue by jkone27** [amplifying-fsharp/sessions#24]
### Session on Improve compiler error inside CE for missed match case

Giacomo in Ams cet  would like to tackle:
https://github.com/dotnet/fsharp/issues/15748

#### Extra

I am not a pro in F# but I am using it in unit tests in my company and for fun projects too, so hopefully I could tackle some compiler error improvement but if it’s too difficult I can try something simpler instead!

**Comment by edgarfgp** [comment]
Hey @jkone27, Thanks for creating this session. We are currently on our summer break. 
We will look at this when we are back and propose a possible date for the session :)

**Comment by jkone27** [comment]
Cheers and enjoy your summer break ! :)

**Comment by edgarfgp** [comment]
@jkone27 Would 2023/09/01 from 15:00 - 16:30 CEST work for you?

**Comment by jkone27** [comment]
It does work! optioned in my calendar

**Comment by dawedawe** [comment]
Thanks again. It was great.
