### ISSUE TITLE
New session about Rider - Put computation expression custom operations at the top of completion list

### ISSUE THREAD

**Issue by jindraivanek** [amplifying-fsharp/sessions#25]
### Session on Rider - Put computation expression custom operations at the top of completion list

Jindřich Ivánek, from Ciklum, in Prague, Czech Republic would like to tackle:
https://youtrack.jetbrains.com/issue/RIDER-15832/Put-custom-operations-at-the-top-of-completion-list-if-its-invoked-on-top-level-inside-computation-expression

**Comment by dawedawe** [comment]
Thanks again. It was great!
