### ISSUE TITLE
New session about Data science basically LLMs

### ISSUE THREAD

**Issue by ConradKash** [amplifying-fsharp/sessions#27]
### Session on Data science basically LLMs

Kakuru Conrad Akankwasa in UTC+3 would like to tackle:
I am new to the field of data science. i haven't had an opportunity to work on a real-world project and get real-life experience and confidence

#### Extra

I am really enthusiastic about data science

**Comment by dawedawe** [comment]
Hello Conrad,

the good people of FsLab have well maintained issues. Maybe there's something in there for you to work on during an Amplifying session:
https://github.com/fslaborg/FSharp.Stats/issues
https://github.com/plotly/Plotly.NET/issues

Once you have decided what exactly you want to work on, we can have a call to talk about the next steps to prepare the session.
