### ISSUE TITLE
New session about Better error handling in FSAC

### ISSUE THREAD

**Issue by pblasucci** [amplifying-fsharp/sessions#30]
### Session on Better error handling in FSAC

Paul Blasucci in CET / CEST would like to tackle:
https://github.com/fsharp/FsAutoComplete

#### Extra

I don't have any special equipment for streaming, but I do have fairly good headphones with a boom mike. Will that be enough? Also, if it matters, I'm planning to do this from my Ubuntu laptop (but I could try to get a dev environment set up on my old Win10 box, if that's better). Thanks!

**Comment by TheAngryByrd** [comment]
> I don't have any special equipment for streaming, but I do have fairly good headphones with a boom mike. Will that be enough?

Yep this should be fine.

> Also, if it matters, I'm planning to do this from my Ubuntu laptop 

We use Zoom so as long as your machine is powerful enough to run zoom and fsac, it should be good.

**Comment by TheAngryByrd** [comment]
@pblasucci How does Friday, November 3rd (2023/10/03) 15:00-16ish CEST work for you?

**Comment by pblasucci** [comment]
Yup. That works great schedule-wise (even if we go a little longer). I'm blocking out my calendar now.

However, I made need to revive my Windows box (and get a new webcam). I've hit a bunch of issues with SDK versions on my primary (Ubuntu) machine.   :'-(

**Comment by dawedawe** [comment]
Done :)
