### ISSUE TITLE
New session about Fsharp Collection Types

### ISSUE THREAD

**Issue by aguluman** [amplifying-fsharp/sessions#31]
### Session on Fsharp Collection Types

Chukwuma Akunyili, from Myself, in +1 GMT would like to tackle:
I would like to dive deep about fsharp collections

#### Extra

I started my fsharp journey in July. And I love the syntax of the language. I noticed there wasn't any person of color I could look up to, so I have decided to become the person of color others can look up too. If you'd let me. But I have to show my merit first.

**Comment by dawedawe** [comment]
Hey @ChukwumaA ,
cool to see you taking action.

I sincerely hope you don't feel somehow alone in our community.
There's [Damian](https://github.com/DamianReeves) from the US, we had him on the [show](https://amplifying-fsharp.github.io/sessions/2023/05/12/) back in May. Maybe you want to connect with him...
There's also [Allister](https://twitter.com/allisterbeharry) from Trinidad, doing cool [stuff](https://bobkonf.de/2021/beharry.html)

I'll look into the issue of FSharp.Collections.Immutable you mentioned to me in the next couple of days, I'm positive we can come up with something.

**Comment by aguluman** [comment]
Thank you. I will connect with them and keep learning.
