### ISSUE TITLE
New session about Amplifying F#

### ISSUE THREAD

**Issue by wdputro** [amplifying-fsharp/sessions#33]
### Session on 

 in  would like to tackle:
I'm a C# Developer just finding out and learning F#. Would love to polish this skill and contribute at the same time.

#### Extra

It's an individual contribution and I would like to start with about 2 Hours/Week commitment.

**Comment by nojaf** [comment]
Hi @wdputro, sorry for the delayed response to your issue.

We appreciate your patience. Your request seems a bit unique compared to our usual workflow. Typically, we host a live-streamed F# OSS session on Fridays. Would you be interested in joining one of these sessions to discuss your issue?

**Comment by nojaf** [comment]
Hello @wdputro,

I think https://amplifying-fsharp.github.io/fsharp-essentials/ would be the best place for this request.
Hope to see you there!
