### ISSUE TITLE
New session about Glutinum

### ISSUE THREAD

**Issue by nojaf** [amplifying-fsharp/sessions#34]
### Session on Glutinum

Florian, from Nojaf BV, in CET would like to tackle:
https://github.com/glutinum-org/cli/issues/24

#### Extra

Hi @mangelmaxime, could I persuade you to do some pairing on this issue as part of an AF stream?
I'm ok with being the driver but could use som handholding to tackle the problem.

**Comment by MangelMaxime** [comment]
Hello @nojaf,

Yes sure we can do a session on Glutinum and fixing that or others issues.
