### ISSUE TITLE
New session about Application to offer Legal Consultancy Services 

### ISSUE THREAD

**Issue by tweri21** [amplifying-fsharp/sessions#35]
### Session on Application to offer Legal Consultancy Services 

Robert Mutwiri Mwongera , from Mwongera Robert Mutwiri Advocates , in GMT +3 would like to tackle:
My lawfirm would like to offer legal consultancy services

**Comment by nojaf** [comment]
Hello, this appears to be beyond the scope of our usual activities. I appreciate your comprehension.
