### ISSUE TITLE
New session about Real-time event visualization using F# and Fable

### ISSUE THREAD

**Issue by object** [amplifying-fsharp/sessions#39]
### Session on Working with Real-time event visualization using F# and Fable

Vagif Abilov, from Miles AS, in CET would like to tackle:
Better contribution to OSS

**Comment by nojaf** [comment]
💯 Many thanks for this proposal!
Would 29/03 work for you?

**Comment by object** [comment]
Oh that's too early. This is just an idea for the presentation. I need to work on it. Need some time. Also need to check out other proposals to get an idea of how it is usually done.

**Comment by nojaf** [comment]
Sure thing, keep us posted on how things are going. No pressure!

**Comment by object** [comment]
I see that most of the sessions are between 1 and 2 hours. Is this a recommended duration of the presentation? Also many sessions are just live coding with no slides. Is this what I should aim?

**Comment by nojaf** [comment]
You can bring your content as you see fit.
There is no minimum or maximum duration, the longer the stream, the less rewatch value it has but you shouldn't overly worry about that.
You can use slides, no slides, code, no codes, ... however, you see fit!

**Comment by edgarfgp** [comment]
@object Could you please let us know a possible date(Friday's) that will work for you so we can schedule this interesting session.

**Comment by object** [comment]
Hi Edgar and Florian, and sorry for the delays. I was perhaps too quick to
announce my session because even though we have been using Akkling Akka.NET
F# API for years, I need to work on material first in order to build an
interesting presentation, and my work/life schedule for the next few weeks
is pretty tight. I will let you know when I have everything I need so we
can schedule this session. On some Friday as you suggested.

Cheers
Vagif

**Comment by nojaf** [comment]
Hi Vagif, thanks for the feedback.
No worries, we can schedule it at your convenience.

**Comment by object** [comment]
Hi Florian and Edgar. While I still haven't prepared enough material to run a session on Akka.NET/Akkling/F#, I have another proposition where I can present on a short notice. I recently upgraded our internal Fable Web application to use latest Fable libraries and .NET 8, and I have built a workshop that I ran a few times internally in NRK (our organization). The workshop is called "Real-time event visualization using F# and Fable" and its plan is listed here: https://github.com/object/FableWorkshop.2024/blob/main/FableWorkshop.md

It takes me about 2 hours to build a Fable application from scratch that uses Saturn Web service to simulate real-time event stream. The client-server communication is implemented using Web sockets.

If this sounds interesting I can run a session when it's a proper time for it (shouldn't we wait until people come back from vacations?), and I can come back to Akka topic when I am ready.

What do you think?

**Comment by nojaf** [comment]
Hey Vagif! That sounds very interesting! Without chatting to anyone from AF, I would propose to keep this as a "Welcome back to school" session in September. We can tap into our F# Essentials crowd with such a session.

@edgarfgp let me know what how that sounds!

**Comment by edgarfgp** [comment]
> Hey Vagif! That sounds very interesting! Without chatting to anyone from AF, I would propose to keep this as a "Welcome back to school" session in September. We can tap into our F# Essentials crowd with such a session.
> 
> @edgarfgp let me know what how that sounds!

Indeed looks interesting to follow up the F# Essentials](https://amplifyingfsharp.io/fsharp-essentials/) lessons. 

I think we can do this the 2ndof 3th week of September?. Will that work for you @object ?

**Comment by object** [comment]
I am on vacation between 11 and 19 of September, so this is in fact 2-3 week. So we need to find different date.

Vagif

**Comment by nojaf** [comment]
Hi Vagif, any chance we can set something up for October?

**Comment by object** [comment]
Yes, we should. Any date suggestions?

**Comment by edgarfgp** [comment]
> Yes, we should. Any date suggestions?

@object Im organising October's sessions. We could have yours on:
- Friday 18th. Time slots between 15:00 - 18:00 CEST
- Friday 25th Time slots between 15:00 - 18:00 CEST

How does this sounds to you ?

**Comment by object** [comment]
Both look good to me, but let me carefully check our family calendar so I
don't overlook anything. I will get back to you with the chosen time.

Vagif

**Comment by object** [comment]
October 18 works best for me. But as we discussed earlier, instead of
Akkling I will be running a live session about building live dashboards
using Fable. I will prepare a description of the session soon.

**Comment by edgarfgp** [comment]
> October 18 works best for me. But as we discussed earlier, instead of Akkling I will be running a live session about building live dashboards using Fable. I will prepare a description of the session soon.


Thanks. Sounds like a plan. Please let us know the slot time between 15:00 - 18:00 CEST 👍

**Comment by object** [comment]
Hi,

I believe 16:00 works best for me. Here's the workshop description.


Real-time event visualization using F# and Fable
<https://github.com/object/FableWorkshop.2024/blob/main/FableWorkshop.md#real-time-event-visualization-using-f-and-fable>
Prerequisites
<https://github.com/object/FableWorkshop.2024/blob/main/FableWorkshop.md#prerequisites>

   1. Visual Studio Code (running on Windows, Linux or MacOS)
   2. Ionide F# plugin (Ionide-fsharp) by Ionide
   3. Basic understanding of F#
   4. .NET Core version 8.0 or later
   5. npm JavaScript package manager

Recommended tools and resources
<https://github.com/object/FableWorkshop.2024/blob/main/FableWorkshop.md#recommended-tools-and-resources>

   1. The Elmish Book <https://zaid-ajaj.github.io/the-elmish-book> by Zaid
   Ajaj (its sample is outdated and currently doesn't build with latest Fable
   packages but it it still a valuable resource that explains Fable/Elmish
   concepts)
   2. An Introduction to Elm <https://guide.elm-lang.org/>, it
   helps understanding of Elmish and MVU architecture
   3. REST Client plugin by Huachao Mao to be be able to execute HTTP
   request right from Visual Studio Code
   4. Chrome browser
   5. Redux DevTools Chrome extension (remember to enable it)

Workshop plan
<https://github.com/object/FableWorkshop.2024/blob/main/FableWorkshop.md#workshop-plan>

   1. Scaffolding a project with SAFE template
   2. Serving the content of a file from a Saturn Web service
   3. Retrieving file content using HTTP requests in a Fable app
   4. Implementing playback of individual lines of a file
   5. Replacing direct calls to Fable.React with Feliz
   6. Adding Bulma CSS and FontAwesome to a Fable app (using CSS F# type
   provider)
   7. From file lines player to events player (parsing text lines with
   Thoth.Json decoder)
   8. Implementing event subscriptions using Web sockets (and Elmish.Bridge)
   9. Adding live tiles (presentation of state changes)
   10. Using Redux DevTools with Fable applications

**Comment by edgarfgp** [comment]
@object Thanks. I will create a PR for  the session page in our website.

**Comment by object** [comment]
Hi again, it's now about 10 days until the session, should it be announced? Also, how should it be run technically? Any tools I should have installed to stream it? Any technical tests we need to perform?

**Comment by edgarfgp** [comment]
> Hi again, it's now about 10 days until the session, should it be announced? Also, how should it be run technically? Any tools I should have installed to stream it? Any technical tests we need to perform?

Hi @object. 

Thanks for reaching out.  Im working on the session page. Regarding tools needed you just need to install zoom and either use  a microphone or some decent headphones.

I was planning to reach out  on Slack to have a quick call to go over the session structure.

Edit: I will be announcing the session tomorrow.

**Comment by edgarfgp** [comment]
Session page is now live at https://amplifyingfsharp.io/sessions/2024/10/18/

**Comment by object** [comment]
Great! 

One last thing, @edgarfgp. I just changed my employer, I no longer work for Miles. I joined Norwegian Broadcasting Corporation and would very much like to replace "Miles AS" with "NRK" in the announcement. I just updated my profile at GitHub.
Thanks in advance!

**Comment by edgarfgp** [comment]
> Great!
> 
> One last thing, @edgarfgp. I just changed my employer, I no longer work for Miles. I joined Norwegian Broadcasting Corporation and would very much like to replace "Miles AS" with "NRK" in the announcement. I just updated my profile at GitHub. Thanks in advance!

It is done now :)

**Comment by object** [comment]
That was superquck, thanks!
