### ISSUE TITLE
New session about FSharp.Formatting

### ISSUE THREAD

**Issue by nhirschey** [amplifying-fsharp/sessions#4]
### Session on FSharp.Formatting

Nicholas Hirschey in Lisbon/London would like to tackle:
https://github.com/fsprojects/FSharp.Formatting

#### Extra

Open to suggestions with FSharp.Formatting. There are probably several small formatting-related issues that could be done. One bigger thing would be ipynb parsing as an input, but that's likely not solvable in a couple hours.

**Comment by nojaf** [comment]
Hi @nhirschey, thanks a bunch for this suggestion.
I think we should go with an issue that is either useful to you or beginner friendly.

Maybe take a look at the [existing issues](https://github.com/fsprojects/FSharp.Formatting/issues) to see if there is anything in there. If nothing really comes to mind then perhaps https://github.com/fsprojects/FSharp.Formatting/issues/778 could be a nice one.

All our current sessions have been on Friday afternoons (European time), would that work for you?

**Comment by nhirschey** [comment]
Hi @nojaf, sorry for the delay in getting back to you. Sure, Friday afternoons generally work after 2pm Lisbon/London time including next week (March 31).

I took a look at the issues. I posted a suggestion for how the table of contents could be added to API docs using an html details element. The `<details>` tag seems to address the original compaint and addresses baronfel's wish for it to be collapsable too. Plus, probably relatively easy to implement ; )

**Comment by nojaf** [comment]
Hi @nhirschey, next Friday would be great if that works. Maybe at 2 PM London time, that would line up with our other sessions.

https://github.com/fsprojects/FSharp.Formatting/issues/778 sounds like a great candidate.

If you can confirm the timing I will create the session on our website.
Are you ok with it being recorded?

**Comment by nhirschey** [comment]
Yes, let’s do next Friday 2pm London time. I’m ok with it being recorded.

**Comment by nojaf** [comment]
Thanks again @nhirschey, we were honoured to have you!
