### ISSUE TITLE
New session about "A gentle introduction to FsLexYacc"

### ISSUE THREAD

**Issue by dawedawe** [amplifying-fsharp/sessions#40]
### Session on A gentle introduction to FsLexYacc

dawe, from https://www.function-type.com/, in CET would like to tackle:
Let's use FsLexYacc to create a lexer and parser for our own little language. With the AST ready, we add an interpreter to fully enjoy our creation.

**Comment by edgarfgp** [comment]
Im looking forward to this one 🙂

**Comment by dawedawe** [comment]
done
