### ISSUE TITLE
New session about Adding drag and drop feature for Ionide file order

### ISSUE THREAD

**Issue by JavkWick** [amplifying-fsharp/sessions#41]
### Session on Adding drag and drop feature for file order to Ionide

Jack Danna aka JavkWick in EST would like to tackle:
I don't have one.

**Comment by nojaf** [comment]
Hi Jack, thanks for showing interest in a session.
Could you give us some pointers on what you would like to do in Ionide?

Is this about dragging/reordering files in the F# explorer tab?

**Comment by JavkWick** [comment]
Howdy Florian,

Apologies for the delay and absolutely.

I think it would be awesome in Ionide (I specifically use the vscode
extension) to be able to reorder the .fsproj within my project by dragging
the files around. This would come in handy for organizing and it is
apparently a feature Rider has. If this is too much work though don't worry
about it. I just wanted to contribute to Amplify F# and this seemed like
something cool we could do.

[image: image.png]
^^ Here is the F# panel in vscode which I am referring to.

TheAngryByrd over on the discord also thought it could be a good idea. He
actually dove into it a bit if you wanted to read his and other's thoughts:
https://discordapp.com/channels/196693847965696000/524660202864377896/1228422659054768138

With regards,
-Jack (aka JavkWick)

**Comment by nojaf** [comment]
Alright, cool! Any chance May 3rd around 9 AM would work for you?

**Comment by nojaf** [comment]
Hi @JavkWick, did you see my message above? Would that work for you?

**Comment by JavkWick** [comment]
Howdy Florian,

Apologies for the delay yet again.

Unfortunately I'll be attending the Stir Trek conf on May 3rd so that
probably won't work. Also I think @TheAngryByrd will also be at Stir Trek
and he had said he was probably the most knowledge about how to add that UI
to Ionide.

I'm also gonna be in Colorado the following Friday May 10th for Lambda Conf
( at which it looks like I might be giving a small F# talk 🤓).

The earliest one I could attend would be May 17th unfortunately at our
usual time, but if you guys wanted to take the idea for the May 10th talk
be my guest. I'll also try and think up some more questions for
Amplifying F# in the meantime.

With regards,
-Jack

**Comment by nojaf** [comment]
No worries, thanks for the update. Enjoy Stir Trek!

**Comment by edgarfgp** [comment]
@JavkWick Could you please let us know a possible date(Friday) that will work for you so we can schedule this interesting session.

**Comment by JavkWick** [comment]
Friday works for me!

**Comment by JavkWick** [comment]
Hey Edgar,

Apologies for misunderstanding your previous email. Friday May 31st
should work for me.

-Jack

**Comment by nojaf** [comment]
Hi @JavkWick, would this Friday work for you?

**Comment by JavkWick** [comment]
Howdy, absolutely!

**Comment by nojaf** [comment]
Hello, it currently is already Friday and I would like to move this one week to have some more breathing room.

Could we do Friday June 14th, 3 PM CEST?

**Comment by JavkWick** [comment]
Sure, no problem.

**Comment by nojaf** [comment]
Done https://amplifyingfsharp.io/sessions/2024/06/14/
