### ISSUE TITLE
tooling

### ISSUE THREAD

**Issue by HcsOmot** [amplifying-fsharp/sessions#44]
### Session on tooling

Tomo Šala, from individal contributor  in CEST would like to tackle:
I'm currently working with elixir and there's one specific thing I'm missing in F# REPL - full blown documentation for built-in functions & modules.

Elixir docs in REPL:
https://hexdocs.pm/elixir/basic-types.html#identifying-functions-and-documentation

#### Extra

I've been playing around with F# and really really like it, but have absolutely no idea where and how to start to bring the documentation into REPL. Would love some help with this if at all possible.

**Comment by dawedawe** [comment]
Hey @HcsOmot ,
we are trying to bring this to F# https://github.com/dotnet/fsharp/pull/17140
In the meantime, you can use the [fsih](https://github.com/dawedawe/fsih) package

**Comment by HcsOmot** [comment]
thank you @dawedawe , didn't know about these. will take a look! cheers!
