### ISSUE TITLE
Resharper JetBrains

### ISSUE THREAD

**Issue by aguluman** [amplifying-fsharp/sessions#55]
### Session on ReSharper JetBrains

Chukwuma Akunyili, from Tenece Professional Services in WAT, would like to tackle:
https://github.com/JetBrains/resharper-fsharp/issues/688

#### Extra

Initially, I used to believe that intellect was determined by race, assuming that one race had solely propelled human progress, leaving another race to simply reap the benefits, leading to a perception of incompetence within the disadvantaged race.

Therefore, I aim to shift this narrative for all interested individuals, emphasizing that everyone has the potential to contribute to the advancement of humanity.

As Edgar once wisely stated, as long as one holds an interest in the given issue, the sky marks just the beginning.

**Comment by dawedawe** [comment]
Hey @aguluman,
thanks for creating the session proposal. To be sure I understand you correctly: You want Rider to auto-create the open-Statement after typing "asyncResult" or is it about auto-adding the nuget reference?
Either way, I think your  next steps would be to get familiar with [resharper-fsharp](https://github.com/JetBrains/resharper-fsharp).
Built it locally on your machine, run it, debug it, let the tests run etc.

**Comment by aguluman** [comment]
Yes, you are right.
I want rider to be able to auto-create the open statement, ```open FsToolkit.ErrorHandling``` when the ```ctrl+.``` command is used, and the option to import missing reference will show, and the user presses the enter key. 
As that is my flow while working in Rider with C#.

I look forward to getting familiar with resharper-fsharp.

**Comment by nojaf** [comment]
You can also checkout previous sessions on Rider:
- https://www.youtube.com/watch?v=BycmFA0UPhg
- https://www.youtube.com/watch?v=U4fZ8nASokc

**Comment by aguluman** [comment]
Sure, will watch them this week.
Thank you.

**Comment by aguluman** [comment]
@nojaf @dawedawe Thank you.

The project is currently running locally, and the tests have been passed as well. 

![image](https://github.com/user-attachments/assets/3ba81640-e483-4308-b55c-4e0c17e7e576)

**Comment by dawedawe** [comment]
Cool, I think the next steps for you are getting a bit familiar with the codebase and try to find an API you could use to create the open statement after certain things have been typed. I would assume that something similar already exists in Resharper.

**Comment by aguluman** [comment]
I just checked. 
This issue, I raised has been fixed by someone else. 

Florian Intellisense for named fields on Rider video was really helpful in understanding the codebase.
