### ISSUE TITLE
A F# Compiler Tour: Reviewing "Scoped Nowarn"

### ISSUE THREAD

**Issue by Martin521** [amplifying-fsharp/sessions#57]
### Session on *A F# Compiler Tour: Reviewing "Scoped Nowarn"*

Martin, from - in CET would like to tackle:
https://github.com/dotnet/fsharp/pull/18049

#### Extra

My goal is to get a thorough review of the above PR. (Or to enable people to review it thoroughly.)
The session could be announced like this:
Are you curious about the F# compiler? How lexing, parsing, service lexing, trivia, diagnostics, configuration work? Follow us on a tour that demonstrates work in all these areas.

**Comment by edgarfgp** [comment]
Thanks Martin for submitting this session. @nojaf do you think we can fit this session in Dec ?

**Comment by nojaf** [comment]
Yes, I'm trying to follow up on the other pending sessions first.
If we can make it happen and it works for Martin, I'd like to have this in December!

**Comment by Martin521** [comment]
December 13 would be great. That's the only Friday in December though that I can make.

**Comment by nojaf** [comment]
Alright, sold, I'll work on a page for this soon(ish)!
Thanks Martin!
