### ISSUE TITLE
New session about Fixing a Fantomas style bug

### ISSUE THREAD

**Issue by josh-degraw** [amplifying-fsharp/sessions#6]
### Session on Fixing a Fantomas style bug

Josh DeGraw, from Pluralsight, in MDT would like to tackle:
https://github.com/fsprojects/fantomas

#### Extra

I'm planning on trying to tackle https://github.com/fsprojects/fantomas/issues/2706, it should be pretty small in scope and hopefully I can get it figured out in one shot 😅. I think April 14 should work best for me as of now.

**Comment by nojaf** [comment]
Hi Josh, this is amazing news! Thanks a bunch, what time would work for you on the 14th?

**Comment by nojaf** [comment]
Hi again @josh-degraw, could we settle for April 14th at 10 am MDT?
That would be 6 pm CEST.

**Comment by josh-degraw** [comment]
> Hi again @josh-degraw, could we settle for April 14th at 10 am MDT?
> That would be 6 pm CEST.

Yes I think that should work!
