### ISSUE TITLE
New session about Anything, but I was thinking FSAC

### ISSUE THREAD

**Issue by nickybaby** [amplifying-fsharp/sessions#7]
### Session on Anything, but I was thinking FSAC

Nick Cloutier in EST would like to tackle:
I just want to contribute to OSS for the first time in a serious way, and I'd like to grow the F# community in someway if possible.

**Comment by nojaf** [comment]
Hi Nick, thanks a bunch for reaching out!
We are happy to organise a session on your behalf!

FSAC is a great topic to work on.
I've asked the maintainers if there is something we could pick up that helps them.

As for timing, would Friday the 21st of April work for you?
If so, what would be your preferred time (EST)?

**Comment by TheAngryByrd** [comment]
hey @nickybaby! I'm glad you want to pick something up from FSAC. 

As far as things to work on, I would say _pick something that bothers you_. This give you a bit more investment into fixing the issue.

If there's nothing you feel strongly about off the top of your head there are issues in other projects related to FSAC that impact the whole experience. (I'm still awaiting access to triage things in FSAC). 

- [proj-info - good first issues](https://github.com/ionide/proj-info/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)
- [ionide - up for grabs](https://github.com/ionide/ionide-vscode-fsharp/labels/up%20for%20grabs)

**Comment by nickybaby** [comment]
Anytime after 2 PM EST is probably ideal.  @nojaf 

I don't really use F# professionally, and I do have some time constraints because I have 2 small kids, but I like the language a lot and want to contribute.  I'll check out those links @TheAngryByrd.

Thank you for the warm welcome. :)

**Comment by nojaf** [comment]
Thanks, Nick, can we settle on Friday, April 21st at 2 PM EST? That would be 8 PM CEST.

Is it ok if we record the session?
What link to your social media can we use for the website? In past sessions, we've typically linked to a Twitter account.

**Comment by nickybaby** [comment]
Sure, and I don't mind if the session is recorded but I don't really have any social media presence.

**Comment by dawedawe** [comment]
Mmh, how about linking to your github profile? Would that be okay for you?

**Comment by nickybaby** [comment]
Sure, of course.

**Comment by dawedawe** [comment]
Jimmy recently labeled a lot of issues  with "help wanted". Maybe there is something in there for you:
https://github.com/fsharp/FsAutoComplete/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22
