### ISSUE TITLE
New session about Implement syntax for creating immutable arrays

### ISSUE THREAD

**Issue by charlesroddie** [amplifying-fsharp/sessions#8]
### Session on Implement syntax for creating immutable arrays

Charles Roddie, from Summatic, in GMT+0 would like to tackle:
https://github.com/dotnet/fsharp/pull/12859

#### Extra

ImmutableArrays https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1094-immarray.md promise to displace mutable arrays as the natural array type in F#.

I made a draft PR to implement the syntax `[: :]` specified in the RFC for creating immutable arrays. I mad this a long time ago and it didn't work. I have no experience in the compiler so I needed some help to get it to work. Edgar on slack told me that I should post on here and would be able to get help! I can fix conflicts before a session is scheduled.

Note that there is some discussion in the discussion thread linked from the rfc about alternative syntaxes. However if we get the PR to work then changing the syntax afterwards to match the conclusion should be straightforward.

**Comment by nojaf** [comment]
Hello Charles,

Thank you for submitting a session proposal, much appreciated!

I would definitely be on board to work on your PR during a session. It would be an interesting use case for us and might have traction in the community. 

Given the state of the RFC, I don't think we can make any guarantees that it will end up in the compiler. The proposal seems a bit in flux and I want to manage expectations on that front. Nevertheless, I see value in the stream regardless of the outcome.

Could you maybe rebase your PR, I would like to take a detailed look at it on my machine.

On a practical note, would Friday, May 5th at 2 pm UK time work for you?

**Comment by charlesroddie** [comment]
That date is good. I'll rebase the PR before then.

**Comment by nojaf** [comment]
Alright, great to hear. We will tag you once we have a draft to put on the website.

**Comment by dawedawe** [comment]
Hey @charlesroddie , I absolutely don't want to stress you, but as Friday is drawing near, could you do the rebase soon, please?
It would really help us to prepare...

**Comment by charlesroddie** [comment]
I tried it but it looks wrong. I think I may have rebased from origin/master but the current is origin/main. Maybe I need to start the rebase again.

**Comment by charlesroddie** [comment]
I've done a merge from main but it's some way from building again.

The build failures I get are:

```fsharp
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4704,5): error : Expected file "C:\Users\charl\source\repos\fsharp\artifacts\obj\TaskPerf\Debug\net7.0\refint\TaskPerf.dll" does not exist.
1>Done building project "TaskPerf.fsproj" -- FAILED.
2>FSC : error FS0246: Unrecognized value '7.0' for --langversion use --langversion:? for complete list
2>Done building project "FSharp.Build.fsproj" -- FAILED.
3>FSC : error FS0074: The type referenced through 'System.Array' is defined in an assembly that is not referenced. You must add a reference to assembly 'The system type 'System.Array' was required but no referenced system DLL contained this type'.
3>Done building project "FSharp.Compiler.Service.fsproj" -- FAILED.
```

The first doesn't seem related and the second I don't know how to pinpoint as it doesn't refer to a file.

**Comment by nojaf** [comment]
Hi @charlesroddie, thanks for working on this.

As your code was originally written a while ago a lot has changed.
Did you perform a `git clean -xdf` to clean up any old artifacts?
You might be in a mixed state of dotnet sdks and other old vs new dependencies.

Also, how are you building the source code? Using the `Build.cmd / build.sh` script or using the new-ish introduced `BUILDING_USING_DOTNET` MSBuild property?

**Comment by charlesroddie** [comment]
OK thanks. Cleaning and using build.cmd worked.

First build error is now related:

```
shift/reduce error at state 59 on terminal RBRACK between {noprec shift(60)} and {noprec reduce(bound:)} - assuming the former because we prefer shift when unable to compare precedences
          time: 00:00:00.0431491
          building goto table...        time: 00:00:00.0027223
          returning tables.
          1 shift/reduce conflicts
          consider setting precedences explicitly using %left %right and %nonassoc on terminals and/or setting explicit
   precedence on rules using %prec
```

I didn't get a build error when testing before the merge so it could be a merge error, could be better error detection now, or could be that I didn't build in the same way last time.

**Comment by charlesroddie** [comment]
Fixed merge issues and branch builds now; thanks to @nojaf for help.
