### ISSUE TITLE
New session about Updating F# Analyzers to net7.0 and using F# Analyzers to restrict the F# language

### ISSUE THREAD

**Issue by DamianReeves** [amplifying-fsharp/sessions#9]
### Session on Updating F# Analyzers to net7.0 and using F# Analyzers to restrict the F# language

Damian Reeves in EDT would like to tackle:
https://github.com/ionide/FSharp.Analyzers.SDK

**Comment by nojaf** [comment]
Hi Damian, thanks a bunch for showing interest in a session here.
We'll try and figure out who could best facilitate this topic and I'll get back to you!

**Comment by dawedawe** [comment]
Hey @DamianReeves,
would Friday, 12.5. work for you?
For the time, we would aim at something during the morning of your time zone (NY) if that's ok for you.

**Comment by DamianReeves** [comment]
Yes that sounds good.
